import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "CozySoul Inc | Miami Properties",
  description: "Generated by create next app",
  icons: {
    icon: "svg/red-logo.svg",
    shortcut: "svg/red-logo.svg",
    apple: "svg/red-logo.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-full w-full bg-white`}>
        {children}
      </body>
    </html>
  );
}
